#!/bin/sh

if ! [ $# -eq 2 ]; then
	echo "Syntax: 002_cert ENABLE|DISABLE <output-script>" >&2
	exit 8
fi

verb="$1"
script="$2"
zbrew=`whence zbrew`
zbrewdir=${zbrew%/*}
zbrewroot=${zbrewdir%/*}

cat <<'EOF' >${script}
#!/bin/sh
SetupCertificates() {
	ZOWE_ROOT="${ZBREW_TGT_ZFSROOT}/usr/lpp/zowe/"
	zbrewZoweConfigFile="${ZBREW_TMP}/zoweconfig.$$.tmp"
	echo "
		HOSTNAME=${ZWE1B0_HOSTNAME}
		IPADDRESS=${ZWE1B0_IPADDRESS}
		VERIFY_CERTIFICATES=${ZWE1B0_VERIFY_CERTIFICATES}
		EXTERNAL_CERTIFICATE=${ZWE1B0_EXTERNAL_CERTIFICATE}
		EXTERNAL_CERTIFICATE_ALIAS=${ZWE1B0_CERTIFICATE_ALIAS}
		EXTERNAL_CERTIFICATE_AUTHORITIES=${ZBREW_CERTIFICATE_AUTHORITES}
		ZOSMF_CERTIFICATE=${ZOS240_ZOSMF_CERTIFICATE}
		KEYSTORE_PASSWORD=${ZWE1B0_KEYSTORE_PASSWORD}
		KEYSTORE_DIRECTORY=${ZWE1B0_KEYSTORE_DIRECTORY}
		KEYSTORE_ALIAS=${ZWE1B0_KEYSTORE_ALIAS}
		ZOWE_USER_ID=${ZWE1B0_ZOWEUSER}
		ZOWE_GROUP_ID=${ZWE1B0_ADMINGRP}
	" >${zbrewZoweConfigFile}
	${ZOWE_ROOT}/bin/zowe-setup-certificates.sh -p ${zbrewZoweConfigFile}    

	return 0
}

EOF

chmod u+x "${script}"
cat << EOF >>${script}
export PATH=${zbrewdir}:\$PATH
. zbrewsetswenv zwe1b0
#set -x
SetupCertificates  
exit $?
EOF
exit 0
