#!/bin/sh

if ! [ $# -eq 2 ]; then
	echo "Syntax: 003_zicfg ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*}
zbrewroot=${zbrewdir%/*}

cat << EOF >${script}
#!/bin/sh
#set -x
export verb="${verb}"
export PATH=${zbrewdir}:\$PATH
. zbrewsetswenv zwe1b0

set +x
zowedir="\${ZBREW_TGT_ZFSROOT}usr/lpp/zowe"
zoweinstancedir="\${ZWE1B0_INSTANCE_ROOT}"
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create ZWE1B0 Update script: ${script}." >&2
	exit 16
fi
chmod u+x "${script}"

if [ "${verb}" = "ENABLE" ]; then
cat <<'EOF' >>${script}
	export JAVA_HOME="${ZBREW_JAVA_HOME}"
	export NODE_HOME="${ZBREW_NODE_HOME}"
	export ZOWE_IP_ADDRESS="${ZWE1B0_IPADDRESS}"
	"${zowedir}/bin/zowe-configure-instance.sh" -c "${zoweinstancedir}"
EOF
else
cat <<'EOF' >>${script}
#
# Remove instance dir here ?
#
EOF
fi
exit 0  
