#!/bin/sh

if ! [ $# -eq 2 ]; then
	echo "Syntax: 003_xmemcfg ENABLE|DISABLE <output-script>" >&2
	exit 8
fi
verb="$1"
script="$2"

zbrew=`whence zbrew`
zbrewdir=${zbrew%/*}
zbrewroot=${zbrewdir%/*}

cat << EOF >${script}
#!/bin/sh
#set -x
export verb="${verb}"
export PATH=${zbrewdir}:\$PATH
. zbrewsetswenv zwe1b0

set +x
authlib="\${ZBREW_TGT_HLQ}ZWE1B0.SZWEAUTH"
srclib="\${ZBREW_TGT_HLQ}ZWE1B0.SZWESAMP"
parmlib="\${ZBREW_TGT_HLQ}PARMLIB"
proclib="\${ZBREW_TGT_HLQ}PROCLIB"
EOF

if [ $? -gt 0 ]; then
	echo "Unable to create ZWE1B0 Update script: ${script}." >&2
	exit 16
fi
chmod u+x "${script}"

if [ "${verb}" = "ENABLE" ]; then
cat <<'EOF' >>${script}
	swesip=`cat "//'${srclib}(ZWESIP00)'"`

	sijcl=`cat "//'${srclib}(ZWESISTC)'"`
	sijcl=`jclReplaceDD "${sijcl}" "ZWESIS01" "STEPLIB" "${ZBREW_TGT_HLQ}ZWE1B0.SZWEAUTH"`
	sijcl=`jclReplaceDD "${sijcl}" "ZWESIS01" "PARMLIB" "${parmlib}"`

	sajcl=`cat "//'${srclib}(ZWESASTC)'"`
	sajcl=`jclReplaceDD "${sajcl}" "ZWESAUX" "STEPLIB" "${ZBREW_TGT_HLQ}ZWE1B0.SZWEAUTH"`
EOF
else
cat <<'EOF' >>${script}
	swesip=''
	sijcl=''
	sajcl=''
EOF
fi

cat <<'EOF' >>${script}
apfregistrar zwe1b0 "${verb}" "${authlib}"
chk "$?" "Unable to ${verb} APF Authorization of ${authlib}"

procregistrar zwe1b0 "${verb}" ZWESISTC "${sijcl}"
chk "$?" "Unable to ${verb} proclib member ${proclib}(ZWESISTC)"

procregistrar zwe1b0 "${verb}" ZWESASTC "${sajcl}"
chk "$?" "Unable to ${verb} proclib member ${proclib}(ZWESASTC)"

profhdr="//* ZWE1B0 start */"
profftr="//* ZWE1B0 end */"

registrar "ZWE1B0" "${verb}" "${parmlib}" "ZWESIP00" "$profhdr" "$profftr" "//*" "*/" "${zwesip}"
chk "$?" "Unable to ${verb} ${parmlib}(ZWESIP00)"

exit $?

EOF
exit 0  
